backend:
  name: git-gateway

media_folder: "content/images" # Folder where user uploaded files should go
public_folder: "content/images"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.yml"
        label: "Startseite"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Banner Titel, name: banner_headline, widget: string}
          - {label: Banner Untertitel, name: banner_subheader, widget: string}
          - {label: Banner Button, name: banner_cta, widget: string}
