backend:
  name: git-gateway
  branch: develop

media_folder: "content/images" # Folder where user uploaded files should go
public_folder: "content/images"

collections: # A list of collections the CMS should be able to edit
  - name: pages
    label: Pages
    label_singular: Page
    files:
      - file: 'content/pages/home.yml'
        label: Startseite
        name: home
        fields:
          - {label: URL, name: url, widget: hidden, default: "/"}
          - {label: Titel, name: title, widget: string}
          - label: Banner
            name: banner
            widget: object
            fields:
              - {label: Überschrift, name: headline, widget: string}
              - {label: Untertitel, name: subheader, widget: string}
              - {label: Button, name: cta, widget: string}
              - {label: Hintergrundbild, name: image, widget: image}

  - name: sections
    label: Sections
    label_singular: Section
    extension: yml
    folder: 'content/sections'
    url: '/'
    create: true
    fields:
      - {label: Titel, name: title, widget: string}
      - label: Teaser
        name: teaser
        widget: object
        fields:
          - {label: Überschrift, name: headline, widget: string}
          - {label: Text, name: copy, widget: string}
          - {label: Bild, name: image, widget: image}

  - name: services
    label: Services
    label_singular: Service
    extension: yml
    folder: 'content/services'
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Sektion, name: section_relation, widget: relation, collection: sections}
      - label: Teaser
        name: teaser
        widget: object
        fields:
          - {label: Überschrift, name: headline, widget: string}
          - {label: Text, name: copy, widget: string}
          - {label: Button, name: cta, widget: string}
          - {label: Bild, name: image, widget: image}

  - name: settings
    label: Site Settings
    files:
      - file: 'content/site.yml'
        label: Global Settings
        name: site
        fields: []
